/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsageIndexRouteImport } from './routes/usage/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as MemoriesIndexRouteImport } from './routes/memories/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as SettingsRetentionRouteImport } from './routes/settings/retention'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as MemoriesSearchRouteImport } from './routes/memories/search'
import { Route as MemoriesMemoryIdRouteImport } from './routes/memories/$memoryId'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as ApiV1StoreRouteImport } from './routes/api/v1/store'
import { Route as ApiV1SearchRouteImport } from './routes/api/v1/search'
import { Route as ApiV1ProfileRouteImport } from './routes/api/v1/profile'
import { Route as ApiV1ForgetRouteImport } from './routes/api/v1/forget'
import { Route as ApiSessionsStartRouteImport } from './routes/api/sessions/start'
import { Route as ApiSessionsRecordRouteImport } from './routes/api/sessions/record'
import { Route as ApiMemoryStoreRouteImport } from './routes/api/memory/store'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryProfileRouteImport } from './routes/api/memory/profile'
import { Route as ApiMemoryForgetRouteImport } from './routes/api/memory/forget'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentsHealthRouteImport } from './routes/api/agents/health'
import { Route as ApiAgentsConnectRouteImport } from './routes/api/agents/connect'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageIndexRoute = UsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRetentionRoute = SettingsRetentionRouteImport.update({
  id: '/settings/retention',
  path: '/settings/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesSearchRoute = MemoriesSearchRouteImport.update({
  id: '/memories/search',
  path: '/memories/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesMemoryIdRoute = MemoriesMemoryIdRouteImport.update({
  id: '/memories/$memoryId',
  path: '/memories/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StoreRoute = ApiV1StoreRouteImport.update({
  id: '/api/v1/store',
  path: '/api/v1/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SearchRoute = ApiV1SearchRouteImport.update({
  id: '/api/v1/search',
  path: '/api/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileRoute = ApiV1ProfileRouteImport.update({
  id: '/api/v1/profile',
  path: '/api/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ForgetRoute = ApiV1ForgetRouteImport.update({
  id: '/api/v1/forget',
  path: '/api/v1/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsStartRoute = ApiSessionsStartRouteImport.update({
  id: '/api/sessions/start',
  path: '/api/sessions/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRecordRoute = ApiSessionsRecordRouteImport.update({
  id: '/api/sessions/record',
  path: '/api/sessions/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryStoreRoute = ApiMemoryStoreRouteImport.update({
  id: '/api/memory/store',
  path: '/api/memory/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/api/memory/search',
  path: '/api/memory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryProfileRoute = ApiMemoryProfileRouteImport.update({
  id: '/api/memory/profile',
  path: '/api/memory/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryForgetRoute = ApiMemoryForgetRouteImport.update({
  id: '/api/memory/forget',
  path: '/api/memory/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsHealthRoute = ApiAgentsHealthRouteImport.update({
  id: '/api/agents/health',
  path: '/api/agents/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsConnectRoute = ApiAgentsConnectRouteImport.update({
  id: '/api/agents/connect',
  path: '/api/agents/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agents/new': typeof AgentsNewRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/memories/search': typeof MemoriesSearchRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/retention': typeof SettingsRetentionRoute
  '/settings/team': typeof SettingsTeamRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/usage/': typeof UsageIndexRoute
  '/api/agents/connect': typeof ApiAgentsConnectRoute
  '/api/agents/health': typeof ApiAgentsHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/profile': typeof ApiMemoryProfileRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/store': typeof ApiMemoryStoreRoute
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/sessions/start': typeof ApiSessionsStartRoute
  '/api/v1/forget': typeof ApiV1ForgetRoute
  '/api/v1/profile': typeof ApiV1ProfileRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/store': typeof ApiV1StoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agents/new': typeof AgentsNewRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/memories/search': typeof MemoriesSearchRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/retention': typeof SettingsRetentionRoute
  '/settings/team': typeof SettingsTeamRoute
  '/agents': typeof AgentsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/memories': typeof MemoriesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/usage': typeof UsageIndexRoute
  '/api/agents/connect': typeof ApiAgentsConnectRoute
  '/api/agents/health': typeof ApiAgentsHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/profile': typeof ApiMemoryProfileRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/store': typeof ApiMemoryStoreRoute
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/sessions/start': typeof ApiSessionsStartRoute
  '/api/v1/forget': typeof ApiV1ForgetRoute
  '/api/v1/profile': typeof ApiV1ProfileRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/store': typeof ApiV1StoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/agents/new': typeof AgentsNewRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/memories/search': typeof MemoriesSearchRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/retention': typeof SettingsRetentionRoute
  '/settings/team': typeof SettingsTeamRoute
  '/agents/': typeof AgentsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/memories/': typeof MemoriesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/usage/': typeof UsageIndexRoute
  '/api/agents/connect': typeof ApiAgentsConnectRoute
  '/api/agents/health': typeof ApiAgentsHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/profile': typeof ApiMemoryProfileRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/store': typeof ApiMemoryStoreRoute
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/sessions/start': typeof ApiSessionsStartRoute
  '/api/v1/forget': typeof ApiV1ForgetRoute
  '/api/v1/profile': typeof ApiV1ProfileRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/store': typeof ApiV1StoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/onboarding'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/agents/new'
    | '/memories/$memoryId'
    | '/memories/search'
    | '/settings/billing'
    | '/settings/retention'
    | '/settings/team'
    | '/agents/'
    | '/analytics/'
    | '/memories/'
    | '/sessions/'
    | '/settings/'
    | '/usage/'
    | '/api/agents/connect'
    | '/api/agents/health'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/profile'
    | '/api/memory/search'
    | '/api/memory/store'
    | '/api/sessions/record'
    | '/api/sessions/start'
    | '/api/v1/forget'
    | '/api/v1/profile'
    | '/api/v1/search'
    | '/api/v1/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/onboarding'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/agents/new'
    | '/memories/$memoryId'
    | '/memories/search'
    | '/settings/billing'
    | '/settings/retention'
    | '/settings/team'
    | '/agents'
    | '/analytics'
    | '/memories'
    | '/sessions'
    | '/settings'
    | '/usage'
    | '/api/agents/connect'
    | '/api/agents/health'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/profile'
    | '/api/memory/search'
    | '/api/memory/store'
    | '/api/sessions/record'
    | '/api/sessions/start'
    | '/api/v1/forget'
    | '/api/v1/profile'
    | '/api/v1/search'
    | '/api/v1/store'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/onboarding'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/agents/new'
    | '/memories/$memoryId'
    | '/memories/search'
    | '/settings/billing'
    | '/settings/retention'
    | '/settings/team'
    | '/agents/'
    | '/analytics/'
    | '/memories/'
    | '/sessions/'
    | '/settings/'
    | '/usage/'
    | '/api/agents/connect'
    | '/api/agents/health'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/profile'
    | '/api/memory/search'
    | '/api/memory/store'
    | '/api/sessions/record'
    | '/api/sessions/start'
    | '/api/v1/forget'
    | '/api/v1/profile'
    | '/api/v1/search'
    | '/api/v1/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AgentsNewRoute: typeof AgentsNewRoute
  MemoriesMemoryIdRoute: typeof MemoriesMemoryIdRoute
  MemoriesSearchRoute: typeof MemoriesSearchRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsRetentionRoute: typeof SettingsRetentionRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UsageIndexRoute: typeof UsageIndexRoute
  ApiAgentsConnectRoute: typeof ApiAgentsConnectRoute
  ApiAgentsHealthRoute: typeof ApiAgentsHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMemoryForgetRoute: typeof ApiMemoryForgetRoute
  ApiMemoryProfileRoute: typeof ApiMemoryProfileRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryStoreRoute: typeof ApiMemoryStoreRoute
  ApiSessionsRecordRoute: typeof ApiSessionsRecordRoute
  ApiSessionsStartRoute: typeof ApiSessionsStartRoute
  ApiV1ForgetRoute: typeof ApiV1ForgetRoute
  ApiV1ProfileRoute: typeof ApiV1ProfileRoute
  ApiV1SearchRoute: typeof ApiV1SearchRoute
  ApiV1StoreRoute: typeof ApiV1StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage/': {
      id: '/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof UsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/retention': {
      id: '/settings/retention'
      path: '/settings/retention'
      fullPath: '/settings/retention'
      preLoaderRoute: typeof SettingsRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/search': {
      id: '/memories/search'
      path: '/memories/search'
      fullPath: '/memories/search'
      preLoaderRoute: typeof MemoriesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$memoryId': {
      id: '/memories/$memoryId'
      path: '/memories/$memoryId'
      fullPath: '/memories/$memoryId'
      preLoaderRoute: typeof MemoriesMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/store': {
      id: '/api/v1/store'
      path: '/api/v1/store'
      fullPath: '/api/v1/store'
      preLoaderRoute: typeof ApiV1StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/search': {
      id: '/api/v1/search'
      path: '/api/v1/search'
      fullPath: '/api/v1/search'
      preLoaderRoute: typeof ApiV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile': {
      id: '/api/v1/profile'
      path: '/api/v1/profile'
      fullPath: '/api/v1/profile'
      preLoaderRoute: typeof ApiV1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/forget': {
      id: '/api/v1/forget'
      path: '/api/v1/forget'
      fullPath: '/api/v1/forget'
      preLoaderRoute: typeof ApiV1ForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/start': {
      id: '/api/sessions/start'
      path: '/api/sessions/start'
      fullPath: '/api/sessions/start'
      preLoaderRoute: typeof ApiSessionsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/record': {
      id: '/api/sessions/record'
      path: '/api/sessions/record'
      fullPath: '/api/sessions/record'
      preLoaderRoute: typeof ApiSessionsRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/store': {
      id: '/api/memory/store'
      path: '/api/memory/store'
      fullPath: '/api/memory/store'
      preLoaderRoute: typeof ApiMemoryStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/api/memory/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/profile': {
      id: '/api/memory/profile'
      path: '/api/memory/profile'
      fullPath: '/api/memory/profile'
      preLoaderRoute: typeof ApiMemoryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/forget': {
      id: '/api/memory/forget'
      path: '/api/memory/forget'
      fullPath: '/api/memory/forget'
      preLoaderRoute: typeof ApiMemoryForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/health': {
      id: '/api/agents/health'
      path: '/api/agents/health'
      fullPath: '/api/agents/health'
      preLoaderRoute: typeof ApiAgentsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/connect': {
      id: '/api/agents/connect'
      path: '/api/agents/connect'
      fullPath: '/api/agents/connect'
      preLoaderRoute: typeof ApiAgentsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AgentsNewRoute: AgentsNewRoute,
  MemoriesMemoryIdRoute: MemoriesMemoryIdRoute,
  MemoriesSearchRoute: MemoriesSearchRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsRetentionRoute: SettingsRetentionRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UsageIndexRoute: UsageIndexRoute,
  ApiAgentsConnectRoute: ApiAgentsConnectRoute,
  ApiAgentsHealthRoute: ApiAgentsHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMemoryForgetRoute: ApiMemoryForgetRoute,
  ApiMemoryProfileRoute: ApiMemoryProfileRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryStoreRoute: ApiMemoryStoreRoute,
  ApiSessionsRecordRoute: ApiSessionsRecordRoute,
  ApiSessionsStartRoute: ApiSessionsStartRoute,
  ApiV1ForgetRoute: ApiV1ForgetRoute,
  ApiV1ProfileRoute: ApiV1ProfileRoute,
  ApiV1SearchRoute: ApiV1SearchRoute,
  ApiV1StoreRoute: ApiV1StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
