/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionsStartRouteImport } from './routes/api/sessions/start'
import { Route as ApiSessionsRecordRouteImport } from './routes/api/sessions/record'
import { Route as ApiMemoryStoreRouteImport } from './routes/api/memory/store'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryProfileRouteImport } from './routes/api/memory/profile'
import { Route as ApiMemoryForgetRouteImport } from './routes/api/memory/forget'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentsHealthRouteImport } from './routes/api/agents/health'
import { Route as ApiAgentsConnectRouteImport } from './routes/api/agents/connect'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsStartRoute = ApiSessionsStartRouteImport.update({
  id: '/api/sessions/start',
  path: '/api/sessions/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRecordRoute = ApiSessionsRecordRouteImport.update({
  id: '/api/sessions/record',
  path: '/api/sessions/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryStoreRoute = ApiMemoryStoreRouteImport.update({
  id: '/api/memory/store',
  path: '/api/memory/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/api/memory/search',
  path: '/api/memory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryProfileRoute = ApiMemoryProfileRouteImport.update({
  id: '/api/memory/profile',
  path: '/api/memory/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryForgetRoute = ApiMemoryForgetRouteImport.update({
  id: '/api/memory/forget',
  path: '/api/memory/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsHealthRoute = ApiAgentsHealthRouteImport.update({
  id: '/api/agents/health',
  path: '/api/agents/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsConnectRoute = ApiAgentsConnectRouteImport.update({
  id: '/api/agents/connect',
  path: '/api/agents/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/agents/connect': typeof ApiAgentsConnectRoute
  '/api/agents/health': typeof ApiAgentsHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/profile': typeof ApiMemoryProfileRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/store': typeof ApiMemoryStoreRoute
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/sessions/start': typeof ApiSessionsStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/agents/connect': typeof ApiAgentsConnectRoute
  '/api/agents/health': typeof ApiAgentsHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/profile': typeof ApiMemoryProfileRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/store': typeof ApiMemoryStoreRoute
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/sessions/start': typeof ApiSessionsStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/agents/connect': typeof ApiAgentsConnectRoute
  '/api/agents/health': typeof ApiAgentsHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/memory/forget': typeof ApiMemoryForgetRoute
  '/api/memory/profile': typeof ApiMemoryProfileRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/store': typeof ApiMemoryStoreRoute
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/sessions/start': typeof ApiSessionsStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/api/agents/connect'
    | '/api/agents/health'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/profile'
    | '/api/memory/search'
    | '/api/memory/store'
    | '/api/sessions/record'
    | '/api/sessions/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/api/agents/connect'
    | '/api/agents/health'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/profile'
    | '/api/memory/search'
    | '/api/memory/store'
    | '/api/sessions/record'
    | '/api/sessions/start'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/api/agents/connect'
    | '/api/agents/health'
    | '/api/auth/$'
    | '/api/memory/forget'
    | '/api/memory/profile'
    | '/api/memory/search'
    | '/api/memory/store'
    | '/api/sessions/record'
    | '/api/sessions/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAgentsConnectRoute: typeof ApiAgentsConnectRoute
  ApiAgentsHealthRoute: typeof ApiAgentsHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMemoryForgetRoute: typeof ApiMemoryForgetRoute
  ApiMemoryProfileRoute: typeof ApiMemoryProfileRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryStoreRoute: typeof ApiMemoryStoreRoute
  ApiSessionsRecordRoute: typeof ApiSessionsRecordRoute
  ApiSessionsStartRoute: typeof ApiSessionsStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/start': {
      id: '/api/sessions/start'
      path: '/api/sessions/start'
      fullPath: '/api/sessions/start'
      preLoaderRoute: typeof ApiSessionsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/record': {
      id: '/api/sessions/record'
      path: '/api/sessions/record'
      fullPath: '/api/sessions/record'
      preLoaderRoute: typeof ApiSessionsRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/store': {
      id: '/api/memory/store'
      path: '/api/memory/store'
      fullPath: '/api/memory/store'
      preLoaderRoute: typeof ApiMemoryStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/api/memory/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/profile': {
      id: '/api/memory/profile'
      path: '/api/memory/profile'
      fullPath: '/api/memory/profile'
      preLoaderRoute: typeof ApiMemoryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/forget': {
      id: '/api/memory/forget'
      path: '/api/memory/forget'
      fullPath: '/api/memory/forget'
      preLoaderRoute: typeof ApiMemoryForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/health': {
      id: '/api/agents/health'
      path: '/api/agents/health'
      fullPath: '/api/agents/health'
      preLoaderRoute: typeof ApiAgentsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/connect': {
      id: '/api/agents/connect'
      path: '/api/agents/connect'
      fullPath: '/api/agents/connect'
      preLoaderRoute: typeof ApiAgentsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAgentsConnectRoute: ApiAgentsConnectRoute,
  ApiAgentsHealthRoute: ApiAgentsHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMemoryForgetRoute: ApiMemoryForgetRoute,
  ApiMemoryProfileRoute: ApiMemoryProfileRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryStoreRoute: ApiMemoryStoreRoute,
  ApiSessionsRecordRoute: ApiSessionsRecordRoute,
  ApiSessionsStartRoute: ApiSessionsStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
